name: Test the action

on:
  workflow_dispatch:
    branches:
      - master
      - main

jobs:
  test_action:
    runs-on: ubuntu-latest
    name: A job to test the action
    steps:
    - uses: actions/checkout@v2

    - name: Execute xpath-action
      id: xpath
      uses: QwerMike/xpath-action@v1
      with:
        filename: ./.github/workflows/cd_catalog.xml
        expression: '//CD/YEAR/text()'

    - name: Get xpath result
      run: echo -e "Result from xpath-action:\n${{ steps.xpath.outputs.result }}"
